# Generated by Django 4.1.6 on 2023-02-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Cumpleaños', models.DateField()),
                ('Nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Genero', models.CharField(max_length=50)),
                ('Año', models.PositiveSmallIntegerField()),
                ('Origen', models.CharField(max_length=50)),
                ('Duracion', models.PositiveSmallIntegerField()),
                ('Director', models.CharField(max_length=100)),
                ('Cast', models.TextField()),
                ('Ranking', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Autor', models.CharField(max_length=100)),
                ('Contenido', models.CharField(max_length=15000)),
                ('Ranking', models.FloatField()),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPeliculas.peliculas')),
            ],
        ),
    ]
