# Generated by Django 4.1.6 on 2023-02-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='Nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='Contenido',
            field=models.CharField(max_length=100000),
        ),
    ]
